M48
; DRILL file {KiCad 9.0.3-9.0.3-0~ubuntu22.04.1} date 2026-08-04T22:10:29+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-04T22:10:29+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3-9.0.3-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X103.5Y-53.5
X103.5Y-116.5
X146.5Y-53.5
X146.5Y-116.5
M30
