//! Baked bitmap font — GENERATED by `display/tools/fontgen.py`, do not hand-edit.
//!
//! An alternate body family for the editor, rendered into the same 10×20 cell as
//! eg's `FONT_10X20` so the fixed character grid (`editor::{CW,CH}`) is untouched
//! (Axis A). Reuses eg's public `mapping::ISO_8859_15`, so the atlas is laid out
//! in that mapping's 192-glyph slot order.

use embedded_graphics::image::ImageRaw;
use embedded_graphics::mono_font::{mapping::ISO_8859_15, DecorationDimensions, MonoFont};
use embedded_graphics::pixelcolor::BinaryColor;
use embedded_graphics::prelude::Size;

/// DejaVu Sans Mono, baked to a 10×20 1-bit cell (ISO-8859-15 repertoire).
pub const DEJAVU_SANS_MONO_10X20: MonoFont = MonoFont {
    image: ImageRaw::<BinaryColor>::new(include_bytes!("dejavu_sans_mono_10x20.raw"), 160),
    glyph_mapping: &ISO_8859_15,
    character_size: Size::new(10, 20),
    character_spacing: 0,
    baseline: 15,
    underline: DecorationDimensions::new(15 + 2, 1),
    strikethrough: DecorationDimensions::new(20 / 2, 1),
};
