#!/usr/bin/env python3
"""Bake a monospace TTF into an embedded-graphics MonoFont for the `display` crate.

Rendering on the device is `embedded-graphics` bitmap `MonoFont`s (see
`display/src/lib.rs`). embedded-graphics ships only one family (X11 "Misc Fixed")
at several sizes, so an *alternate* family has to be baked offline into the same
`MonoFont` shape: a 1-bit glyph atlas + a glyph→slot mapping.

The trick that keeps this tiny: eg's `FONT_10X20` reuses the shared, public
`mapping::ISO_8859_15` (atlas 160 px wide = 16 glyphs/row, baseline 15). If we
lay our atlas out in the *same 192-glyph slot order*, we can reuse that mapping
verbatim and only emit a new `.raw` + a `MonoFont` const. So this script bakes to
a fixed CW×CH=10×20 cell in ISO-8859-15 order.

  Regenerate (fonts are NOT vendored in-repo — they're OFL, fetch as needed):
    python3 display/tools/fontgen.py \
        --ttf ~/Library/Fonts/JetBrainsMono-Medium.ttf \
        --name jetbrains_mono --const JETBRAINS_MONO_10X20

Outputs, next to the crate source:
    display/src/fonts/<name>_10x20.raw   (4800 bytes: 160x240 1-bit, MSB-first, set bit = ink)
    display/src/fonts/<name>.rs          (the `pub const <CONST>: MonoFont` module)
And a self-check preview PNG under the scratchpad for eyeballing.
"""
import argparse
import os
from PIL import Image, ImageDraw, ImageFont

CW, CH = 10, 20          # cell size, must match editor::{CW,CH}
COLS = 16                # glyphs per atlas row (160 px / 10) — matches eg
BASELINE = 15            # matches eg FONT_10X20
INK_THRESHOLD = 128      # gray < threshold -> ink (pure 1-bit, no AA)
# Codepoints Pillow would draw as an ugly .notdef box — blank them instead.
BLANK = {0x7F, 0xA0, 0xAD}


def iso_8859_15_slots():
    """The 192 codepoints in mapping::ISO_8859_15 order (decoded from its range
    string in embedded-graphics 0.8: mono_font/mapping.rs)."""
    s = []
    s += range(0x20, 0x7F + 1)          # 0..95   ASCII + DEL
    s += range(0xA0, 0xA3 + 1)          # 96..99
    s += [0x20AC, 0xA5, 0x160, 0xA7, 0x161]  # € ¥ Š § š
    s += range(0xA9, 0xB3 + 1)          # 105..115
    s += [0x17D]                        # Ž
    s += range(0xB5, 0xB7 + 1)          # 117..119
    s += [0x17E]                        # ž
    s += range(0xB9, 0xBB + 1)          # 121..123
    s += [0x152, 0x153, 0x178]          # Œ œ Ÿ
    s += range(0xBF, 0xFF + 1)          # 127..191
    slots = list(s)
    assert len(slots) == 192, len(slots)
    return slots


def largest_size_for_width(path, max_adv):
    """Biggest integer px size whose monospace advance fits max_adv (fit-by-size,
    the strategy the 1-bit preview showed renders cleanly)."""
    for px in range(28, 6, -1):
        f = ImageFont.truetype(path, px)
        if f.getlength("m") <= max_adv:
            return px, f
    return 8, ImageFont.truetype(path, 8)


def render_cell(font, cp):
    """Render one codepoint into a CW×CH 1-bit cell -> list[CH] of CW-bit rows
    (bit set = ink). Baseline at BASELINE, pen at x=0; anything outside the cell
    is clipped, exactly as the device would."""
    if cp in BLANK:
        return [0] * CH
    pad = 8
    canvas = Image.new("L", (CW + 2 * pad, CH + 2 * pad), 255)
    ImageDraw.Draw(canvas).text((pad, pad + BASELINE), chr(cp), font=font, fill=0, anchor="ls")
    cell = canvas.crop((pad, pad, pad + CW, pad + CH))
    px = cell.load()
    rows = []
    for y in range(CH):
        bits = 0
        for x in range(CW):
            if px[x, y] < INK_THRESHOLD:
                bits |= 1 << (CW - 1 - x)   # MSB = leftmost pixel (x=0)
        rows.append(bits)
    return rows


def pack_atlas(cells):
    """cells: list[192] of list[CH] bitrows -> flat MSB-first 1-bit atlas bytes,
    160 px wide (20 bytes/row), 12 glyph-rows tall = 4800 bytes."""
    n = len(cells)
    rows_of_glyphs = (n + COLS - 1) // COLS
    width_px = COLS * CW                       # 160
    row_bytes = width_px // 8                   # 20
    height_px = rows_of_glyphs * CH             # 240
    buf = bytearray(row_bytes * height_px)
    for i, cell in enumerate(cells):
        gx, gy = (i % COLS) * CW, (i // COLS) * CH
        for ry, bits in enumerate(cell):
            y = gy + ry
            for x in range(CW):
                if (bits >> (CW - 1 - x)) & 1:
                    px = gx + x
                    buf[y * row_bytes + px // 8] |= 0x80 >> (px % 8)
    return bytes(buf), width_px


def emit_rust(const_name, raw_name, title):
    return f'''//! Baked bitmap font — GENERATED by `display/tools/fontgen.py`, do not hand-edit.
//!
//! An alternate body family for the editor, rendered into the same 10×20 cell as
//! eg's `FONT_10X20` so the fixed character grid (`editor::{{CW,CH}}`) is untouched
//! (Axis A). Reuses eg's public `mapping::ISO_8859_15`, so the atlas is laid out
//! in that mapping's 192-glyph slot order.

use embedded_graphics::image::ImageRaw;
use embedded_graphics::mono_font::{{mapping::ISO_8859_15, DecorationDimensions, MonoFont}};
use embedded_graphics::pixelcolor::BinaryColor;
use embedded_graphics::prelude::Size;

/// {title}, baked to a 10×20 1-bit cell (ISO-8859-15 repertoire).
pub const {const_name}: MonoFont = MonoFont {{
    image: ImageRaw::<BinaryColor>::new(include_bytes!("{raw_name}"), 160),
    glyph_mapping: &ISO_8859_15,
    character_size: Size::new(10, 20),
    character_spacing: 0,
    baseline: 15,
    underline: DecorationDimensions::new(15 + 2, 1),
    strikethrough: DecorationDimensions::new(20 / 2, 1),
}};
'''


def self_check(cells, slots, out_png):
    """Reconstruct a sample string straight from the baked cells (proving slot
    order + bit packing) and save an upscaled preview."""
    idx = {cp: i for i, cp in enumerate(slots)}
    lines = ["The quick brown fox", "jumps 0O o1lI| {}[]", "Typoena — € œ Š “x”"]
    scale = 8
    W = max(len(l) for l in lines) * CW
    H = len(lines) * CH
    img = Image.new("L", (W, H), 255)
    px = img.load()
    for r, line in enumerate(lines):
        for c, ch in enumerate(line):
            cell = cells[idx.get(ord(ch), idx[ord("?")])]
            for ry, bits in enumerate(cell):
                for x in range(CW):
                    if (bits >> (CW - 1 - x)) & 1:
                        px[c * CW + x, r * CH + ry] = 0
    img.resize((W * scale, H * scale), Image.NEAREST).save(out_png)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ttf", required=True)
    ap.add_argument("--name", default="jetbrains_mono")
    ap.add_argument("--const", dest="const_name", default="JETBRAINS_MONO_10X20")
    ap.add_argument("--title", default=None, help="human family name for the doc comment")
    ap.add_argument("--outdir", default=os.path.join(os.path.dirname(__file__), "..", "src", "fonts"))
    ap.add_argument("--preview", default=os.environ.get("SCRATCH", "/tmp") + "/fontgen_selfcheck.png")
    args = ap.parse_args()

    px, font = largest_size_for_width(args.ttf, CW)
    print(f"font size = {px}px (advance = {font.getlength('m'):.1f}px)")

    slots = iso_8859_15_slots()
    cells = [render_cell(font, cp) for cp in slots]
    raw, width_px = pack_atlas(cells)
    assert width_px == 160 and len(raw) == 4800, (width_px, len(raw))

    os.makedirs(args.outdir, exist_ok=True)
    raw_name = f"{args.name}_10x20.raw"
    with open(os.path.join(args.outdir, raw_name), "wb") as f:
        f.write(raw)
    title = args.title or args.name.replace("_", " ").title()
    with open(os.path.join(args.outdir, f"{args.name}.rs"), "w") as f:
        f.write(emit_rust(args.const_name, raw_name, title))
    self_check(cells, slots, args.preview)
    print(f"wrote {raw_name} ({len(raw)} B), {args.name}.rs, preview {args.preview}")


if __name__ == "__main__":
    main()
